#!/bin/bash
mkdir -p docs
lein ancient > docs/ancient.txt

if [ "$(uname)" == "Darwin" ]; then
  sed -i '' '/up-to-date/d' docs/ancient.txt
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  sed -i '/up-to-date/d' docs/ancient.txt
fi

./fail-if-nonempty docs/ancient.txt &&
lein kibit > docs/kibit.txt &&
./fail-if-nonempty docs/kibit.txt &&
lein bikeshed &&
lein spec -f d -C > docs/specs.txt &&
lein docs
